language: android
jdk:
    - oraclejdk8
android:
    components:
        - platform-tools
        - tools
        - build-tools-26.0.1
        - android-26
        - extra-google-google_play_services
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-android-support
        - addon-google_apis-google-26
script:
    ./gradlew build jacocoTestReport assembleAndroidTest --stacktrace
after_success:
    - bash <(curl -s https://codecov.io/bash) -t 6fab7ae1-f07e-46bf-a6f2-aebc5b8adc78
