language: android
jdk:
    - oraclejdk8
android:
    components:
        - platform-tools
        - tools
        - build-tools-25.0.3
        - android-25
        - extra-google-google_play_services
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-android-support
        - addon-google_apis-google-25
script:
    ./gradlew build jacocoTestReport assembleAndroidTest --stacktrace
#notifications:
#    slack:
#        rooms:
#            - capstone-snaption:uLoSExpS3w6h7MWDHQfExWth#android-build
#        template:
#            - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
#            - ":push_parrot: :push_parrot: :push_parrot:"
after_success:
    - bash <(curl -s https://codecov.io/bash) -t 6fab7ae1-f07e-46bf-a6f2-aebc5b8adc78
