language: android
jdk:
    - oraclejdk8
env:
    matrix:
        - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a ANDROID_TAG=google_apis
android:
    components:
        - platform-tools
        - tools
        - build-tools-25.0.2
        - $ANDROID_TARGET
        - android-25
        - extra-google-google_play_services
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-android-support
        - addon-google_apis-google-25
        - sys-img-armeabi-v7a-google_apis-21
before_script:
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --tag $ANDROID_TAG
    - emulator -avd test -no-skin -no-audio -no-window &
script:
    - android-wait-for-emulator
    - adb devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedAndroidTest
notifications:
    slack: capstone-snaption:uLoSExpS3w6h7MWDHQfExWth
